// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'media_metadata.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MediaMetadata _$MediaMetadataFromJson(Map<String, dynamic> json) =>
    MediaMetadata(
      itemId: json['itemId'] as String,
      key: json['key'] as String,
      guid: json['guid'] as String?,
      studio: json['studio'] as String?,
      type: json['type'] as String,
      title: json['title'] as String,
      titleSort: json['titleSort'] as String?,
      contentRating: json['contentRating'] as String?,
      summary: json['summary'] as String?,
      rating: (json['rating'] as num?)?.toDouble(),
      audienceRating: (json['audienceRating'] as num?)?.toDouble(),
      userRating: (json['userRating'] as num?)?.toDouble(),
      year: (json['year'] as num?)?.toInt(),
      originallyAvailableAt: json['originallyAvailableAt'] as String?,
      thumb: json['thumb'] as String?,
      art: json['art'] as String?,
      duration: (json['duration'] as num?)?.toInt(),
      addedAt: (json['addedAt'] as num?)?.toInt(),
      updatedAt: (json['updatedAt'] as num?)?.toInt(),
      lastPlayedAt: (json['lastPlayedAt'] as num?)?.toInt(),
      seriesTitle: json['seriesTitle'] as String?,
      seriesImageId: json['seriesImageId'] as String?,
      seriesArt: json['seriesArt'] as String?,
      seriesId: json['seriesId'] as String?,
      seasonTitle: json['seasonTitle'] as String?,
      seasonImageId: json['seasonImageId'] as String?,
      seasonId: json['seasonId'] as String?,
      parentIndex: (json['parentIndex'] as num?)?.toInt(),
      index: (json['index'] as num?)?.toInt(),
      seriesTheme: json['seriesTheme'] as String?,
      resumePositionMs: (json['resumePositionMs'] as num?)?.toInt(),
      playCount: (json['playCount'] as num?)?.toInt(),
      leafCount: (json['leafCount'] as num?)?.toInt(),
      watchedEpisodeCount: (json['watchedEpisodeCount'] as num?)?.toInt(),
      unwatchedCount: (json['unwatchedCount'] as num?)?.toInt(),
      childCount: (json['childCount'] as num?)?.toInt(),
      role: (json['Role'] as List<dynamic>?)
          ?.map((e) => CastRole.fromJson(e as Map<String, dynamic>))
          .toList(),
      audioLanguage: json['audioLanguage'] as String?,
      subtitleLanguage: json['subtitleLanguage'] as String?,
      playlistItemID: (json['playlistItemID'] as num?)?.toInt(),
      playQueueItemID: (json['playQueueItemID'] as num?)?.toInt(),
      libraryId: (json['libraryId'] as num?)?.toInt(),
      ratingImage: json['ratingImage'] as String?,
      audienceRatingImage: json['audienceRatingImage'] as String?,
      subtype: json['subtype'] as String?,
      extraType: (json['extraType'] as num?)?.toInt(),
      primaryExtraKey: json['primaryExtraKey'] as String?,
      clearLogo: json['clearLogo'] as String?,
    );

Map<String, dynamic> _$MediaMetadataToJson(MediaMetadata instance) =>
    <String, dynamic>{
      'itemId': instance.itemId,
      'key': instance.key,
      'guid': instance.guid,
      'studio': instance.studio,
      'type': instance.type,
      'title': instance.title,
      'titleSort': instance.titleSort,
      'contentRating': instance.contentRating,
      'summary': instance.summary,
      'rating': instance.rating,
      'audienceRating': instance.audienceRating,
      'userRating': instance.userRating,
      'year': instance.year,
      'originallyAvailableAt': instance.originallyAvailableAt,
      'thumb': instance.thumb,
      'art': instance.art,
      'duration': instance.duration,
      'addedAt': instance.addedAt,
      'updatedAt': instance.updatedAt,
      'lastPlayedAt': instance.lastPlayedAt,
      'seriesTitle': instance.seriesTitle,
      'seriesImageId': instance.seriesImageId,
      'seriesArt': instance.seriesArt,
      'seriesId': instance.seriesId,
      'seasonTitle': instance.seasonTitle,
      'seasonImageId': instance.seasonImageId,
      'seasonId': instance.seasonId,
      'parentIndex': instance.parentIndex,
      'index': instance.index,
      'seriesTheme': instance.seriesTheme,
      'resumePositionMs': instance.resumePositionMs,
      'playCount': instance.playCount,
      'leafCount': instance.leafCount,
      'watchedEpisodeCount': instance.watchedEpisodeCount,
      'unwatchedCount': instance.unwatchedCount,
      'childCount': instance.childCount,
      'Role': instance.role,
      'audioLanguage': instance.audioLanguage,
      'subtitleLanguage': instance.subtitleLanguage,
      'playlistItemID': instance.playlistItemID,
      'playQueueItemID': instance.playQueueItemID,
      'libraryId': instance.libraryId,
      'ratingImage': instance.ratingImage,
      'audienceRatingImage': instance.audienceRatingImage,
      'subtype': instance.subtype,
      'extraType': instance.extraType,
      'primaryExtraKey': instance.primaryExtraKey,
      'clearLogo': instance.clearLogo,
    };
